branch-defaults:
  master:
    environment: ${AWS_EB_ENV_NAME}
global:
  application_name: ${AWS_APP_NAME}
  default_ec2_keyname: elasticbeanstalk:${AWS_EC2_NAME}
  default_platform: Node.js 12 running on 64bit Amazon Linux 2/5.2.3
  default_region: ${AWS_REGION}
  sc: git